<?php
    /*
        !INSTALL BETTER COMMENTS EXTENSION TO SEE THE RESULT
        TODO: ADD THE USER CIRCLE AND THE COLOR PER CELL SELECTED
        TODO: ADD COLUMN TO THE ACTUAL TABLE
        TODO: REAL TIME EDITING NG TABLE
        TODO: REAL TIME UPDATING NG TABLE
        TODO: REAL TIME DELETING OF ROWS?? (OPTIONAL)
        TODO: DROP DOWN FEATURE
        TODO: EXPORT THE FILE IN EXCEL FORMAT
    */
?>